export const START_LOADING = "START_LOADING";
export const STOP_LOADING = "STOP_LOADING";

export const START_RESEND_LOADING = "START_RESEND_LOADING";
export const STOP_RESEND_LOADING = "STOP_RESEND_LOADING";

export const START_SECONDARY_LOADING = "START_SECONDARY_LOADING"
export const STOP_SECONDARY_LOADING = "STOP_SECONDARY_LOADING"

export const START_TERTIARY_LOADING = "START_TERTIARY_LOADING"
export const STOP_TERTIARY_LOADING = "STOP_TERTIARY_LOADING"

export const ERROR_MESSAGE = "ERROR_MESSAGE"

export const STATUS_CODE = "STATUS_CODE";

export const SHOW_SUCCESS_BOX = "SHOW_SUCCESS_BOX"

export const IS_NO_MORE_DATA = "IS_NO_MORE_DATA"

export const IS_SUCCESS = "IS_SUCCESS";
export const IS_ERROR = "IS_ERROR";

/**
 * Home
 */
export const MAIN_CATEGORY = "MAIN_CATEGORY"
export const PROMOTION_PRODUCT = "PROMOTION_PRODUCT"
export const LATEST_PRODUCT = "LATEST_PRODUCT"
export const BEST_SELLING_PRODICT = "BEST_SELLING_PRODICT"
export const PRODUCT_BY_CATEGORY = "PRODUCT_BY_CATEGORY"
export const BANNER_LIST = "BANNER_LIST"
export const AD_LIST = "AD_LIST"
export const BUY_ONE_GET_ONE_LIST = "BUY_ONE_GET_ONE_LIST";
export const POP_UP_BANNER = "POP_UP_BANNER";
export const GET_BRAND = "GET_BRAND"

/**
 * Authentication
 */
export const CITY_LIST = "CITY_LIST"
export const TOWNSHIP_LIST = "TOWNSHIP_LIST"
export const CLEAR_CITY_LIST = "CLEAR_CITY_LIST"
export const CLEAR_TOWNSHIP_LIST = "CLEAR_TOWN_LIST"
export const RESEND_MESSAGE = "RESEND_MESSAGE"

/**
 * MyAccount
 */
export const USER_ACCOUNT_INFO = "USER_ACCOUNT_INFO"
export const GET_WISH_LIST_PRODUCT = "GET_WISH_LIST_PRODUCT"
export const SET_SUCCESS_MESSAGE = "SET_SUCCESS_MESSAGE"
export const GET_TERMS_AND_CONDITIONS = "GET_TERMS_AND_CONDITIONS"

/**
 * ProductDetails
 */
export const PRODUCT_DETAILS = "PRODUCT_DETAILS"
export const CLEAR_PRODUCT_DETAILS = "CLEAR_PRODUCT_DETAILS"
export const RELATED_PRODUCT_BY_CATEGORY = "RELATED_PRODUCT_BY_CATEGORY"
export const GET_VARIANT_VALUE = "GET_VARIANT_VALUE"
export const GET_Q_AND_A_LIST = "GET_Q_AND_A_LIST"
export const GET_Q_AND_A_LIST_BY_USER = "GET_Q_AND_A_LIST_BY_USER"
export const GET_QUESTION_COUNT = "GET_QUESTION_COUNT"
export const SAVE_QA_ID = "SAVE_QA_ID";
/**
 * Shopping Cart
 */
export const SHOPPING_CART_DETAIL = "SHOPPING_CART_DETAIL"

export const AVAILABLE_PRODUCT_LIST = "AVAILABLE_PRODUCT_LIST"
export const OUT_OF_STOCK_PRODUCT_LIST = "OUT_OF_STOCK_PRODUCT_LIST"
export const STOCK_LEFT_PRODUCT_LIST = "STOCK_LEFT_PRODUCT_LIST"
export const TOTAL_AMOUNT = "TOTAL_AMOUNT"

export const ORDER_ID = "ORDER_ID"
export const BANK_LIST = "BANK_LIST"
export const PAYMENT_SERVICE_DETAIL = "PAYMENT_SERVICE_DETAIL"

/**
 * Product Search
 */
export const GET_TAG_LIST = "GET_TAG_LIST"
export const GET_PRODUCT_SEARCH_LIST = "GET_PRODUCT_SEARCH_LIST"
export const GET_PRODUCT_SEARCH_COUNT = "GET_PRODUCT_SEARCH_COUNT"
export const GET_PRODUCT_SUGGESTION_LIST = "GET_PRODUCT_SUGGESTION_LIST"
export const CLEAR_DATA_LIST = "CLEAR_DATA_LIST"
export const BOUGHT_TOGETHER_PRODUCT_LIST = "BOUGHT_TOGETHER_PRODUCT_LIST"

/**
 * Order History
 */
export const GET_ORDER_HISTORY_LIST = "GET_ORDER_HISTORY_LIST"
export const GET_VOUCHER_NO_SUGGESTION = "GET_VOUCHER_NO_SUGGESTION"

/**
 * Order Detail
 */
export const GET_CART_DETAIL = "GET_CART_DETAIL"
export const GET_ORDER_DETAIL = "GET_ORDER_DETAIL"
export const GET_BANK_LIST = "GET_BANK_LIST"
export const SET_ORDER_ID = "SET_ORDER_ID"
export const CANCEL_ORDER = "CANCEL_ORDER"
export const GET_POS_VOUCHER = "GET_POS_VOUCHER"
export const GET_ORDER_MESSAGE = "GET_ORDER_MESSAGE"

/** 
* Payment
*/
export const POST_KBZ_PAYMENT = "POST_KBZ_PAYMENT"
export const POST_WAVE_PAYMENT = "POST_WAVE_PAYMENT"
export const GET_TRANSACTION_ID = "GET_TRANSACTION_ID"
export const GET_PAYMENT_SERVICE_BY_ID = "GET_PAYMENT_SERVICE_BY_ID"

/** 
 * Product List
 */
export const SET_DATA_EXIST = "SET_DATA_EXIST"


/**
 * Notification
 */
export const GET_NOTIFICATION = "GET_NOTIFICATION"
export const SET_NO_MORE_DATA = "SET_NO_MORE_DATA"
export const SET_PAGE_DEFAULT = "SET_PAGE_DEFAULT"
export const UPDATE_NOTIFICATION = "UPDATE_NOTIFICATION"
export const CHANGE_NOTI_COUNT = "CHANGE_NOTI_COUNT"
export const SHOW_HIDE_NOTIFICATION = "SHOW_HIDE_NOTIFICATION"

/**
* Shipping Warranty Policy Terms & Conditions
*/
export const GET_SHIPPING = "GET_SHIPPING"
export const GET_WARRANTY = "GET_WARRANTY"
export const GET_POLICY = "GET_POLICY"
export const GET_TERMS = "GET_TERMS"
export const GET_INSTALLATION = "GET_INSTALLATION"
export const GET_PREORDER = "GET_PREORDER"

/**
* Shipping Warranty Policy PreOrderTC With ID
*/
export const GET_SHIPPING_ID = "GET_SHIPPING_ID"
export const GET_WARRANTY_ID = "GET_WARRANTY_ID"
export const GET_POLICY_ID = "GET_POLICY_ID"
export const GET_INSTALLATION_ID = "GET_INSTALLATION_ID"
export const GET_PREORDER_ID = "GET_PREORDER_ID"

/**
 * Bycategory
 */
export const SET_SUB_CATEGORY_LIST = "SET_SUB_CATEGORY_LIST"
export const SET_MAIN_CATEGORYDETAIL = "SET_MAIN_CATEGORYDETAIL"
export const SET_PRODUCT_BY_BRAND = "SET_PRODUCT_BY_BRAND"
export const SET_MAIN_CATEGORY = "SET_MAIN_CATEGORY"

/**
 * Brand
 */
export const PRODUCT_BY_BRAND = "PRODUCT_BY_BRAND"
export const PRODUCT_COUNT_BRAND = "PRODUCT_COUNT_BRAND"

/**
 * Delivery Address
 */
export const GET_DELIVERY_ADDRESS = "GET_DELIVERY_ADDRESS"
export const CHANGED_SELECTED_VAL = "CHANGED_SELECTED_VAL"